FROM alpine:latest
LABEL version="1.0"
LABEL maintainer="Ken Lu <a26331057@gmail.com>"
# TODO: checking if aws-cli is needed for auth docker on pulling images in codepipeline
# ENV AWSCLI_VERSION="1.16.283"
# RUN apk add --update \
#     python \
#     python-dev \
#     py-pip \
#     build-base \
#     && pip install awscli==$AWSCLI_VERSION --upgrade --user \
#     && apk --purge -v del py-pip \
#     && rm -rf /var/cache/apk/*
